---

name: validate

on:
  push:
    branches:
      - '*'

jobs:
  ci:
    strategy:
      matrix:
        distribution:  [AlmaLinux, RedHat]

    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@main
    
    - name: Set up Python 3.11
      uses: actions/setup-python@main
      with:
        python-version: 3.11
    
    - name: Install Python module for manipulating kickstart files
      run: |
        python -m pip install --upgrade pip
        pip install --requirement requirements.txt

    - name: Create Kickstart config from jinja template
      run: |
         jinja --data distribution/${{matrix.distribution}}.json ks.cfg.j2 --output ks.cfg

    - name: Validate Kickstart file
      run: |
        ksvalidator --version RHEL8 ks.cfg
